# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CourseBookNew' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CourseBookNew
pod 'RealmSwift', '~> 3.3'
end
